export type AppEnv = {
  NEXT_PUBLIC_SUPABASE_URL: string;
  NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
  NEXT_PUBLIC_FIREBASE_API_KEY: string;
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
  FIREBASE_ADMIN_PROJECT_ID: string;
  FIREBASE_ADMIN_CLIENT_EMAIL: string;
  FIREBASE_ADMIN_PRIVATE_KEY: string;
  ANTHROPIC_API_KEY: string;
  OPENAI_API_KEY: string;
  PET_TALKER_LLM_PROVIDER: 'anthropic' | 'openai';
  PET_TALKER_ANTHROPIC_MODEL: string;
  PET_TALKER_OPENAI_MODEL: string;
  COST_ANALYSIS_LLM_PROVIDER: 'anthropic' | 'openai';
  COST_ANALYSIS_ANTHROPIC_MODEL: string;
  COST_ANALYSIS_OPENAI_MODEL: string;
};
